---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cpu
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: social
  data_path: data/
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 5 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: false
model:
  name: GRANMixtureBernoulli
  num_mix_component: 20
  is_sym: false
  block_size: 4
  sample_stride: 1
  max_num_nodes: 201
  hidden_dim: 128
  embedding_dim: 128
  num_GNN_layers: 7
  num_GNN_prop: 3
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.3
  lr_decay_epoch: [100000000] # no decay
  num_workers: 0
  max_epoch: 3000
  batch_size: 25
  display_iter: 5
  snapshot_epoch: 5
  valid_epoch: 5
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 30
  resume_dir: # /Users/alexdavies/Documents/Year_1/Project/GRAN_social/exp/GRAN/GRANMixtureBernoulli_social_2022-Jun-08-20-06-40_64617/
  resume_model: # model_snapshot_0000030.pth
test:
  batch_size: 1
  num_workers: 4
  num_test_gen: 4 # number of generated samples
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 4
  vis_num_row: 2 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: /Users/alexdavies/Documents/Year_1/Project/D-GRAN/exp/GRAN/GRANMixtureBernoulli_social_2022-Jun-10-20-15-47_86584/
  test_model_name: model_snapshot_0000020.pth
